export type ComtradeCountry = {
  code: number;
  name: string;
  iso2: string;
  iso3: string;
};

export const COMTRADE_COUNTRIES: ComtradeCountry[] = [
  { code: 4, name: "Afghanistan", iso2: "AF", iso3: "AFG" },
  { code: 8, name: "Albania", iso2: "AL", iso3: "ALB" },
  { code: 10, name: "Antarctica", iso2: "AQ", iso3: "ATA" },
  { code: 12, name: "Algeria", iso2: "DZ", iso3: "DZA" },
  { code: 16, name: "American Samoa", iso2: "AS", iso3: "ASM" },
  { code: 20, name: "Andorra", iso2: "AD", iso3: "AND" },
  { code: 24, name: "Angola", iso2: "AO", iso3: "AGO" },
  { code: 28, name: "Antigua and Barbuda", iso2: "AG", iso3: "ATG" },
  { code: 31, name: "Azerbaijan", iso2: "AZ", iso3: "AZE" },
  { code: 32, name: "Argentina", iso2: "AR", iso3: "ARG" },
  { code: 36, name: "Australia", iso2: "AU", iso3: "AUS" },
  { code: 40, name: "Austria", iso2: "AT", iso3: "AUT" },
  { code: 44, name: "Bahamas", iso2: "BS", iso3: "BHS" },
  { code: 48, name: "Bahrain", iso2: "BH", iso3: "BHR" },
  { code: 50, name: "Bangladesh", iso2: "BD", iso3: "BGD" },
  { code: 51, name: "Armenia", iso2: "AM", iso3: "ARM" },
  { code: 52, name: "Barbados", iso2: "BB", iso3: "BRB" },
  { code: 56, name: "Belgium", iso2: "BE", iso3: "BEL" },
  { code: 60, name: "Bermuda", iso2: "BM", iso3: "BMU" },
  { code: 64, name: "Bhutan", iso2: "BT", iso3: "BTN" },
  { code: 68, name: "Bolivia (Plurinational State of)", iso2: "BO", iso3: "BOL" },
  { code: 70, name: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH" },
  { code: 72, name: "Botswana", iso2: "BW", iso3: "BWA" },
  { code: 74, name: "Bouvet Island", iso2: "BV", iso3: "BVT" },
  { code: 76, name: "Brazil", iso2: "BR", iso3: "BRA" },
  { code: 84, name: "Belize", iso2: "BZ", iso3: "BLZ" },
  { code: 86, name: "British Indian Ocean Territory", iso2: "IO", iso3: "IOT" },
  { code: 90, name: "Solomon Islands", iso2: "SB", iso3: "SLB" },
  { code: 92, name: "British Virgin Islands", iso2: "VG", iso3: "VGB" },
  { code: 96, name: "Brunei Darussalam", iso2: "BN", iso3: "BRN" },
  { code: 100, name: "Bulgaria", iso2: "BG", iso3: "BGR" },
  { code: 104, name: "Myanmar", iso2: "MM", iso3: "MMR" },
  { code: 108, name: "Burundi", iso2: "BI", iso3: "BDI" },
  { code: 112, name: "Belarus", iso2: "BY", iso3: "BLR" },
  { code: 116, name: "Cambodia", iso2: "KH", iso3: "KHM" },
  { code: 120, name: "Cameroon", iso2: "CM", iso3: "CMR" },
  { code: 124, name: "Canada", iso2: "CA", iso3: "CAN" },
  { code: 132, name: "Cabo Verde", iso2: "CV", iso3: "CPV" },
  { code: 136, name: "Cayman Islands", iso2: "KY", iso3: "CYM" },
  { code: 140, name: "Central African Republic", iso2: "CF", iso3: "CAF" },
  { code: 144, name: "Sri Lanka", iso2: "LK", iso3: "LKA" },
  { code: 148, name: "Chad", iso2: "TD", iso3: "TCD" },
  { code: 152, name: "Chile", iso2: "CL", iso3: "CHL" },
  { code: 156, name: "China", iso2: "CN", iso3: "CHN" },
  { code: 162, name: "Christmas Island", iso2: "CX", iso3: "CXR" },
  { code: 166, name: "Cocos (Keeling) Islands", iso2: "CC", iso3: "CCK" },
  { code: 170, name: "Colombia", iso2: "CO", iso3: "COL" },
  { code: 174, name: "Comoros", iso2: "KM", iso3: "COM" },
  { code: 175, name: "Mayotte", iso2: "YT", iso3: "MYT" },
  { code: 178, name: "Congo", iso2: "CG", iso3: "COG" },
  { code: 180, name: "Democratic Republic of the Congo", iso2: "CD", iso3: "COD" },
  { code: 184, name: "Cook Islands", iso2: "CK", iso3: "COK" },
  { code: 188, name: "Costa Rica", iso2: "CR", iso3: "CRI" },
  { code: 191, name: "Croatia", iso2: "HR", iso3: "HRV" },
  { code: 192, name: "Cuba", iso2: "CU", iso3: "CUB" },
  { code: 196, name: "Cyprus", iso2: "CY", iso3: "CYP" },
  { code: 203, name: "Czechia", iso2: "CZ", iso3: "CZE" },
  { code: 204, name: "Benin", iso2: "BJ", iso3: "BEN" },
  { code: 208, name: "Denmark", iso2: "DK", iso3: "DNK" },
  { code: 212, name: "Dominica", iso2: "DM", iso3: "DMA" },
  { code: 214, name: "Dominican Republic", iso2: "DO", iso3: "DOM" },
  { code: 218, name: "Ecuador", iso2: "EC", iso3: "ECU" },
  { code: 222, name: "El Salvador", iso2: "SV", iso3: "SLV" },
  { code: 226, name: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ" },
  { code: 231, name: "Ethiopia", iso2: "ET", iso3: "ETH" },
  { code: 232, name: "Eritrea", iso2: "ER", iso3: "ERI" },
  { code: 233, name: "Estonia", iso2: "EE", iso3: "EST" },
  { code: 234, name: "Faroe Islands", iso2: "FO", iso3: "FRO" },
  { code: 238, name: "Falkland Islands (Malvinas)", iso2: "FK", iso3: "FLK" },
  { code: 239, name: "South Georgia and the South Sandwich Islands", iso2: "GS", iso3: "SGS" },
  { code: 242, name: "Fiji", iso2: "FJ", iso3: "FJI" },
  { code: 246, name: "Finland", iso2: "FI", iso3: "FIN" },
  { code: 248, name: "Åland Islands", iso2: "AX", iso3: "ALA" },
  { code: 250, name: "France", iso2: "FR", iso3: "FRA" },
  { code: 254, name: "French Guiana", iso2: "GF", iso3: "GUF" },
  { code: 258, name: "French Polynesia", iso2: "PF", iso3: "PYF" },
  { code: 260, name: "French Southern Territories", iso2: "TF", iso3: "ATF" },
  { code: 262, name: "Djibouti", iso2: "DJ", iso3: "DJI" },
  { code: 266, name: "Gabon", iso2: "GA", iso3: "GAB" },
  { code: 268, name: "Georgia", iso2: "GE", iso3: "GEO" },
  { code: 270, name: "Gambia", iso2: "GM", iso3: "GMB" },
  { code: 275, name: "State of Palestine", iso2: "PS", iso3: "PSE" },
  { code: 276, name: "Germany", iso2: "DE", iso3: "DEU" },
  { code: 288, name: "Ghana", iso2: "GH", iso3: "GHA" },
  { code: 292, name: "Gibraltar", iso2: "GI", iso3: "GIB" },
  { code: 296, name: "Kiribati", iso2: "KI", iso3: "KIR" },
  { code: 300, name: "Greece", iso2: "GR", iso3: "GRC" },
  { code: 304, name: "Greenland", iso2: "GL", iso3: "GRL" },
  { code: 308, name: "Grenada", iso2: "GD", iso3: "GRD" },
  { code: 312, name: "Guadeloupe", iso2: "GP", iso3: "GLP" },
  { code: 316, name: "Guam", iso2: "GU", iso3: "GUM" },
  { code: 320, name: "Guatemala", iso2: "GT", iso3: "GTM" },
  { code: 324, name: "Guinea", iso2: "GN", iso3: "GIN" },
  { code: 328, name: "Guyana", iso2: "GY", iso3: "GUY" },
  { code: 332, name: "Haiti", iso2: "HT", iso3: "HTI" },
  { code: 334, name: "Heard Island and McDonald Islands", iso2: "HM", iso3: "HMD" },
  { code: 336, name: "Holy See", iso2: "VA", iso3: "VAT" },
  { code: 340, name: "Honduras", iso2: "HN", iso3: "HND" },
  { code: 344, name: "China, Hong Kong Special Administrative Region", iso2: "HK", iso3: "HKG" },
  { code: 348, name: "Hungary", iso2: "HU", iso3: "HUN" },
  { code: 352, name: "Iceland", iso2: "IS", iso3: "ISL" },
  { code: 356, name: "India", iso2: "IN", iso3: "IND" },
  { code: 360, name: "Indonesia", iso2: "ID", iso3: "IDN" },
  { code: 364, name: "Iran (Islamic Republic of)", iso2: "IR", iso3: "IRN" },
  { code: 368, name: "Iraq", iso2: "IQ", iso3: "IRQ" },
  { code: 372, name: "Ireland", iso2: "IE", iso3: "IRL" },
  { code: 376, name: "Israel", iso2: "IL", iso3: "ISR" },
  { code: 380, name: "Italy", iso2: "IT", iso3: "ITA" },
  { code: 384, name: "Côte d’Ivoire", iso2: "CI", iso3: "CIV" },
  { code: 388, name: "Jamaica", iso2: "JM", iso3: "JAM" },
  { code: 392, name: "Japan", iso2: "JP", iso3: "JPN" },
  { code: 398, name: "Kazakhstan", iso2: "KZ", iso3: "KAZ" },
  { code: 400, name: "Jordan", iso2: "JO", iso3: "JOR" },
  { code: 404, name: "Kenya", iso2: "KE", iso3: "KEN" },
  { code: 408, name: "Democratic People's Republic of Korea", iso2: "KP", iso3: "PRK" },
  { code: 410, name: "Republic of Korea", iso2: "KR", iso3: "KOR" },
  { code: 414, name: "Kuwait", iso2: "KW", iso3: "KWT" },
  { code: 417, name: "Kyrgyzstan", iso2: "KG", iso3: "KGZ" },
  { code: 418, name: "Lao People's Democratic Republic", iso2: "LA", iso3: "LAO" },
  { code: 422, name: "Lebanon", iso2: "LB", iso3: "LBN" },
  { code: 426, name: "Lesotho", iso2: "LS", iso3: "LSO" },
  { code: 428, name: "Latvia", iso2: "LV", iso3: "LVA" },
  { code: 430, name: "Liberia", iso2: "LR", iso3: "LBR" },
  { code: 434, name: "Libya", iso2: "LY", iso3: "LBY" },
  { code: 438, name: "Liechtenstein", iso2: "LI", iso3: "LIE" },
  { code: 440, name: "Lithuania", iso2: "LT", iso3: "LTU" },
  { code: 442, name: "Luxembourg", iso2: "LU", iso3: "LUX" },
  { code: 446, name: "China, Macao Special Administrative Region", iso2: "MO", iso3: "MAC" },
  { code: 450, name: "Madagascar", iso2: "MG", iso3: "MDG" },
  { code: 454, name: "Malawi", iso2: "MW", iso3: "MWI" },
  { code: 458, name: "Malaysia", iso2: "MY", iso3: "MYS" },
  { code: 462, name: "Maldives", iso2: "MV", iso3: "MDV" },
  { code: 466, name: "Mali", iso2: "ML", iso3: "MLI" },
  { code: 470, name: "Malta", iso2: "MT", iso3: "MLT" },
  { code: 474, name: "Martinique", iso2: "MQ", iso3: "MTQ" },
  { code: 478, name: "Mauritania", iso2: "MR", iso3: "MRT" },
  { code: 480, name: "Mauritius", iso2: "MU", iso3: "MUS" },
  { code: 484, name: "Mexico", iso2: "MX", iso3: "MEX" },
  { code: 492, name: "Monaco", iso2: "MC", iso3: "MCO" },
  { code: 496, name: "Mongolia", iso2: "MN", iso3: "MNG" },
  { code: 498, name: "Republic of Moldova", iso2: "MD", iso3: "MDA" },
  { code: 499, name: "Montenegro", iso2: "ME", iso3: "MNE" },
  { code: 500, name: "Montserrat", iso2: "MS", iso3: "MSR" },
  { code: 504, name: "Morocco", iso2: "MA", iso3: "MAR" },
  { code: 508, name: "Mozambique", iso2: "MZ", iso3: "MOZ" },
  { code: 512, name: "Oman", iso2: "OM", iso3: "OMN" },
  { code: 516, name: "Namibia", iso2: "NA", iso3: "NAM" },
  { code: 520, name: "Naoero", iso2: "NR", iso3: "NRU" },
  { code: 524, name: "Nepal", iso2: "NP", iso3: "NPL" },
  { code: 528, name: "Netherlands (Kingdom of the)", iso2: "NL", iso3: "NLD" },
  { code: 531, name: "Curaçao", iso2: "CW", iso3: "CUW" },
  { code: 533, name: "Aruba", iso2: "AW", iso3: "ABW" },
  { code: 534, name: "Sint Maarten (Dutch part)", iso2: "SX", iso3: "SXM" },
  { code: 535, name: "Bonaire, Sint Eustatius and Saba", iso2: "BQ", iso3: "BES" },
  { code: 540, name: "New Caledonia", iso2: "NC", iso3: "NCL" },
  { code: 548, name: "Vanuatu", iso2: "VU", iso3: "VUT" },
  { code: 554, name: "New Zealand", iso2: "NZ", iso3: "NZL" },
  { code: 558, name: "Nicaragua", iso2: "NI", iso3: "NIC" },
  { code: 562, name: "Niger", iso2: "NE", iso3: "NER" },
  { code: 566, name: "Nigeria", iso2: "NG", iso3: "NGA" },
  { code: 570, name: "Niue", iso2: "NU", iso3: "NIU" },
  { code: 574, name: "Norfolk Island", iso2: "NF", iso3: "NFK" },
  { code: 578, name: "Norway", iso2: "NO", iso3: "NOR" },
  { code: 580, name: "Northern Mariana Islands", iso2: "MP", iso3: "MNP" },
  { code: 581, name: "United States Minor Outlying Islands", iso2: "UM", iso3: "UMI" },
  { code: 583, name: "Micronesia (Federated States of)", iso2: "FM", iso3: "FSM" },
  { code: 584, name: "Marshall Islands", iso2: "MH", iso3: "MHL" },
  { code: 585, name: "Palau", iso2: "PW", iso3: "PLW" },
  { code: 586, name: "Pakistan", iso2: "PK", iso3: "PAK" },
  { code: 591, name: "Panama", iso2: "PA", iso3: "PAN" },
  { code: 598, name: "Papua New Guinea", iso2: "PG", iso3: "PNG" },
  { code: 600, name: "Paraguay", iso2: "PY", iso3: "PRY" },
  { code: 604, name: "Peru", iso2: "PE", iso3: "PER" },
  { code: 608, name: "Philippines", iso2: "PH", iso3: "PHL" },
  { code: 612, name: "Pitcairn", iso2: "PN", iso3: "PCN" },
  { code: 616, name: "Poland", iso2: "PL", iso3: "POL" },
  { code: 620, name: "Portugal", iso2: "PT", iso3: "PRT" },
  { code: 624, name: "Guinea-Bissau", iso2: "GW", iso3: "GNB" },
  { code: 626, name: "Timor-Leste", iso2: "TL", iso3: "TLS" },
  { code: 630, name: "Puerto Rico", iso2: "PR", iso3: "PRI" },
  { code: 634, name: "Qatar", iso2: "QA", iso3: "QAT" },
  { code: 638, name: "Réunion", iso2: "RE", iso3: "REU" },
  { code: 642, name: "Romania", iso2: "RO", iso3: "ROU" },
  { code: 643, name: "Russian Federation", iso2: "RU", iso3: "RUS" },
  { code: 646, name: "Rwanda", iso2: "RW", iso3: "RWA" },
  { code: 652, name: "Saint Barthélemy", iso2: "BL", iso3: "BLM" },
  { code: 654, name: "Saint Helena", iso2: "SH", iso3: "SHN" },
  { code: 659, name: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA" },
  { code: 660, name: "Anguilla", iso2: "AI", iso3: "AIA" },
  { code: 662, name: "Saint Lucia", iso2: "LC", iso3: "LCA" },
  { code: 663, name: "Saint Martin (French Part)", iso2: "MF", iso3: "MAF" },
  { code: 666, name: "Saint Pierre and Miquelon", iso2: "PM", iso3: "SPM" },
  { code: 670, name: "Saint Vincent and the Grenadines", iso2: "VC", iso3: "VCT" },
  { code: 674, name: "San Marino", iso2: "SM", iso3: "SMR" },
  { code: 678, name: "Sao Tome and Principe", iso2: "ST", iso3: "STP" },
  { code: 682, name: "Saudi Arabia", iso2: "SA", iso3: "SAU" },
  { code: 686, name: "Senegal", iso2: "SN", iso3: "SEN" },
  { code: 688, name: "Serbia", iso2: "RS", iso3: "SRB" },
  { code: 690, name: "Seychelles", iso2: "SC", iso3: "SYC" },
  { code: 694, name: "Sierra Leone", iso2: "SL", iso3: "SLE" },
  { code: 702, name: "Singapore", iso2: "SG", iso3: "SGP" },
  { code: 703, name: "Slovakia", iso2: "SK", iso3: "SVK" },
  { code: 704, name: "Viet Nam", iso2: "VN", iso3: "VNM" },
  { code: 705, name: "Slovenia", iso2: "SI", iso3: "SVN" },
  { code: 706, name: "Somalia", iso2: "SO", iso3: "SOM" },
  { code: 710, name: "South Africa", iso2: "ZA", iso3: "ZAF" },
  { code: 716, name: "Zimbabwe", iso2: "ZW", iso3: "ZWE" },
  { code: 724, name: "Spain", iso2: "ES", iso3: "ESP" },
  { code: 728, name: "South Sudan", iso2: "SS", iso3: "SSD" },
  { code: 729, name: "Sudan", iso2: "SD", iso3: "SDN" },
  { code: 732, name: "Western Sahara", iso2: "EH", iso3: "ESH" },
  { code: 740, name: "Suriname", iso2: "SR", iso3: "SUR" },
  { code: 744, name: "Svalbard and Jan Mayen Islands", iso2: "SJ", iso3: "SJM" },
  { code: 748, name: "Eswatini", iso2: "SZ", iso3: "SWZ" },
  { code: 752, name: "Sweden", iso2: "SE", iso3: "SWE" },
  { code: 756, name: "Switzerland", iso2: "CH", iso3: "CHE" },
  { code: 760, name: "Syrian Arab Republic", iso2: "SY", iso3: "SYR" },
  { code: 762, name: "Tajikistan", iso2: "TJ", iso3: "TJK" },
  { code: 764, name: "Thailand", iso2: "TH", iso3: "THA" },
  { code: 768, name: "Togo", iso2: "TG", iso3: "TGO" },
  { code: 772, name: "Tokelau", iso2: "TK", iso3: "TKL" },
  { code: 776, name: "Tonga", iso2: "TO", iso3: "TON" },
  { code: 780, name: "Trinidad and Tobago", iso2: "TT", iso3: "TTO" },
  { code: 784, name: "United Arab Emirates", iso2: "AE", iso3: "ARE" },
  { code: 788, name: "Tunisia", iso2: "TN", iso3: "TUN" },
  { code: 792, name: "Türkiye", iso2: "TR", iso3: "TUR" },
  { code: 795, name: "Turkmenistan", iso2: "TM", iso3: "TKM" },
  { code: 796, name: "Turks and Caicos Islands", iso2: "TC", iso3: "TCA" },
  { code: 798, name: "Tuvalu", iso2: "TV", iso3: "TUV" },
  { code: 800, name: "Uganda", iso2: "UG", iso3: "UGA" },
  { code: 804, name: "Ukraine", iso2: "UA", iso3: "UKR" },
  { code: 807, name: "North Macedonia", iso2: "MK", iso3: "MKD" },
  { code: 818, name: "Egypt", iso2: "EG", iso3: "EGY" },
  { code: 826, name: "United Kingdom of Great Britain and Northern Ireland", iso2: "GB", iso3: "GBR" },
  { code: 831, name: "Guernsey", iso2: "GG", iso3: "GGY" },
  { code: 832, name: "Jersey", iso2: "JE", iso3: "JEY" },
  { code: 833, name: "Isle of Man", iso2: "IM", iso3: "IMN" },
  { code: 834, name: "United Republic of Tanzania", iso2: "TZ", iso3: "TZA" },
  { code: 840, name: "United States of America", iso2: "US", iso3: "USA" },
  { code: 842, name: "United States", iso2: "US", iso3: "USA" },
  { code: 850, name: "United States Virgin Islands", iso2: "VI", iso3: "VIR" },
  { code: 854, name: "Burkina Faso", iso2: "BF", iso3: "BFA" },
  { code: 858, name: "Uruguay", iso2: "UY", iso3: "URY" },
  { code: 860, name: "Uzbekistan", iso2: "UZ", iso3: "UZB" },
  { code: 862, name: "Venezuela (Bolivarian Republic of)", iso2: "VE", iso3: "VEN" },
  { code: 876, name: "Wallis and Futuna Islands", iso2: "WF", iso3: "WLF" },
  { code: 882, name: "Samoa", iso2: "WS", iso3: "WSM" },
  { code: 887, name: "Yemen", iso2: "YE", iso3: "YEM" },
  { code: 894, name: "Zambia", iso2: "ZM", iso3: "ZMB" },
];
